[tool.ruff]
target-version = "py313"
line-length = 120
indent-width = 4

[tool.ruff.lint]
ignore = ["ISC001", "DJ001"]
select = [
    "E",   # PEP8 errors (syntax, indentation)
    "F",   # Pyflakes (dead code, unused imports)
    "DJ",  # Django-specific
    "UP",  # pyupgrade
    "SIM", # flake8-simplify
    "I",   # isort
]
fixable = ["ALL"]
unfixable = []
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
exclude = [
    ".venv",
    "**/migrations/**",
    ".vscode"
]

[tool.ruff.format]
exclude = [
    ".venv",
    "**/migrations/**",
    ".vscode"
]
